booking/urls.py
from django.urls import path, include
from . import views


# BOOKING APP URLS


app_name = "booking"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:apartment_id>/', views.apartment_view, name='apartment'),
    path('apartments/', views.ApartmentsView.as_view(), name='apartments'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('search/', include('haystack.urls',)),

]

config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from search import views

urlpatterns = [
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path('booking/search', views.search, name='search'),
    path("users/", include("django_news_blog.users.urls", namespace="users")),
    path('auth/', include('social_django.urls', namespace='social')),
    path('auth/', include('rest_framework_social_oauth2.urls')),
    path("accounts/", include("allauth.urls")),
    path('booking/', include("booking.urls", namespace="booking")),
    path('', include('cms.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

django_news_blog/users/urls.py
from django.urls import path

from django_news_blog.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

booking/models.py
from datetime import datetime
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models import Q



# Create your models here.


class Apartment(models.Model):
    title = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=20)
    description = models.TextField(blank=True)
    apartment_price = models.IntegerField()
    bedrooms = models.IntegerField()
    bathrooms = models.DecimalField(max_digits=2, decimal_places=1)
    garage = models.IntegerField(default=0)
    size = models.IntegerField()
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/')
    list_date = models.DateTimeField(default=datetime.now, blank=True)
        
    def price_by_date(self, date_obj, date_obj2):
        return self.price.filter(
                Q(price_start_date__lte=date_obj2) & Q(price_end_date__gte=date_obj)
            ).first()

    def __str__(self):
        return self.title

class ApartmentImages(models.Model):
    apartment = models.ForeignKey(Apartment, on_delete="models.CASCADE", related_name="image")
    image = models.ImageField("image")

    def __str__(self):
        return self.image.url


class ApartmentPrices(models.Model):
    apartment = models.ForeignKey(Apartment, on_delete="models.CASCADE", related_name="price")
    price_start_date = models.DateField(blank=True, null=True)
    price_end_date = models.DateField(blank=True, null=True)
    price = models.IntegerField()

    def __str__(self):
        return self.apartment.title


class Reservation(models.Model):
    apartment = models.ForeignKey(Apartment, related_name='reservations',
                                  on_delete=models.CASCADE, blank=True, null=True)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    name = models.CharField(default="", max_length=200)

    def __str__(self):
        return self.name

django_news_blog/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

booking/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Reservation
from django.forms import TextInput


class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = [
            'start_date',
            'end_date',
            'name',
        ]
        widgets = {
            'start_date': TextInput(attrs={'id': 'datepicker'}),
            'end_date': TextInput(attrs={'id': 'datepicker2'}),
        }

django_news_blog/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

booking/views.py
import datetime
import json
from datetime import date, timedelta
from booking.models import Apartment, Reservation, ApartmentPrices
from django.shortcuts import render, reverse, get_object_or_404
from django.views import generic
from django.views.generic import  TemplateView
from django.http import HttpResponseRedirect
from booking.forms import ReservationForm



# 1. uzeti start i end iz forme
# 2. uzeti sve start i end iz cijena
# 3. usporediti start end forme sa start end cijenama
# 4. vratiti samo matcheve sa cijenama
#
#
#
#
#
#
#
#

def apartment_view(request, apartment_id):

    reservation = Reservation.objects.filter(apartment__pk=apartment_id)
    apartment = get_object_or_404(Apartment, pk=apartment_id)
    context = {}
    context['apartment'] = apartment

    unavailable = []
    for start, end in apartment.reservations.values_list('start_date', 'end_date'):
        while start <= end:
            unavailable.append(start.strftime('%-d-%m-%Y'))
            start += datetime.timedelta(days=1)
    form = ReservationForm()
    context['unavailable_dates'] = json.dumps(unavailable)
    context['form'] = form

    if request.method == 'GET':
        form = ReservationForm()
        
    elif request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            context = {}
            reservation = form.save(commit=False)
            reservation.apartment = apartment
            reservation.save()        
            start_date = request.POST.get('start_date', None)
            end_date = request.POST.get('end_date', None)
            sdate = datetime.datetime.strptime(start_date, '%Y-%m-%d') #start
            edate = datetime.datetime.strptime(end_date ,'%Y-%m-%d') #end
            prices_by_date = apartment.price_by_date(sdate, edate)

            user_dates = [sdate + datetime.timedelta(days=x) for x in range((edate-sdate).days + 1)]
            user_date_list = []
            for day in user_dates:
                user_date_list.append(day.strftime('%d,%m,%Y'))
          
            context['price_per_day'] = prices_by_date.price
            context['total_price'] =  len(user_date_list) * prices_by_date.price    
            context['unavailable_dates'] = json.dumps(unavailable)
            context['form'] = form
            context['apartment'] = apartment           
            context['date_start'] = start_date
            context['date_end'] = end_date 
            form.save()
            return render(request, "booking/apartment.html", context)
            
    return render(request, 'booking/apartment.html', context)


class ApartmentsView(generic.ListView):
    context_object_name = 'apartment_list'
    template_name = 'booking/apartments.html'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super(ApartmentsView, self).get_context_data(**kwargs)
        return context

    def get_queryset(self):
        category_pk = self.request.GET.get('pk', None)
        if category_pk:
            return Apartment.objects.order_by("-list_date")
        return Apartment.objects.order_by("-list_date")


class IndexView(generic.ListView):

    template_name = 'booking/index.html'
    context_object_name = 'latest_apartment_list'

    def get_queryset(self):
        return Apartment.objects.all().order_by("-list_date")[:6]


class ContactView(TemplateView):
    template_name = "booking/contact.html"

django_news_blog/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

django_news_blog/templates/booking/apartment.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<head>
    <title>jQuery UI Datepicker - Display inline</title>
    <link rel="stylesheet" href="{% static 'assets/css/all.css' %}">
    <link rel="stylesheet"
        href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/black-tie/jquery-ui.min.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>

    <script type="text/javascript">
        var unavailableDates = "{{ unavailable_dates }}"
        unavailableDates = unavailableDates.replace(/&quot;/g, "").replace(/]/g, "").replace(/ /g, "").replace("[", "").split(",")

        function unavailable(date) {
            dmy = date.getDate() + "-" + (date.getMonth() + 1) + "-" + date.getFullYear();
            if ($.inArray(dmy, unavailableDates) == -1) {
                return [true, ""];
            } else {
                return [false, "", "Unavailable"];
            }
        }
        console.log(unavailableDates);

        $(function () {
            $("#datepicker").datepicker({
                dateFormat: 'yy-mm-dd',
                beforeShowDay: unavailable
            })
        })

        $(function () {
            $("#datepicker2").datepicker({
                dateFormat: 'yy-mm-dd',
                beforeShowDay: unavailable
            })
        });

        $(function () {
            $("#datepicker3").datepicker({
                dateFormat: 'yy-mm-dd',
                numberOfMonths: 3,
                beforeShowDay: unavailable,

            })
        });

    </script>
</head>


<body>

    <section id="top-bar" class="p-3">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <i class="fas fa-phone"></i> (617)-555-5555
                </div>
                <div class="text-center col-md-4">
                    <i class="fas fa-envelope-open"></i> contact@rentpal.co
                </div>
                <div class="col-md-4">
                    <div class="social text-right">
                        <a href="#">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a href="#">
                            <i class="fab fa-facebook"></i>
                        </a>
                        <a href="#">
                            <i class="fab fa-linkedin"></i>
                        </a>
                        <a href="#">
                            <i class="fab fa-instagram"></i>
                        </a>
                        <a href="#">
                            <i class="fab fa-pinterest"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    {% include "partials/_navbar_booking.html" %}
    {% if date_start or date_end  %}
    {% for price in prices %}

    <h1>{{ price.price_start_date }}</h1>
    <h1>{{ price.price_end_date }}</h1>
    <h1>{{ price.price }}</h1>

    {% endfor %}
    <h1>Start Date: {{ date_start }}</h1>
    <h1>End Date: {{ date_end }}</h1>
    <h1>Price Per Day: ${{ price_per_day }}$</h1>
    <h1>Total: ${{ total_price }}$</h1>
    {% endif %}
    <!-- Listing -->
    <section id="listing" class="py-4">
        <h1 class="text-center">{{ apartment.title }}</h1>
        <h3 class="text-center"></h3>
        <div class="container">
            <a href="http://localhost:8000/booking/apartments/" class="btn btn-light mb-4">Back To Listings</a>
            <div class="row">
                <div class="col-md-9">
                    <!-- Home Main Image -->
                    <img src="{{ apartment.photo_main.url }}" alt="" class="img-main img-fluid mb-3">
                    <!-- Thumbnails -->
                    <div class="row mb-5 thumbs">
                        <div class="col-md-2">
                            <a href="{{ apartment.image.all.0 }}" data-lightbox="home-images">
                                <img src="{{ apartment.image.all.0 }}" alt="" class="img-fluid">
                            </a>
                        </div>
                        <div class="col-md-2">
                            <a href="{{ apartment.image.all.1 }}" data-lightbox="home-images">
                                <img src="{{ apartment.image.all.1 }}" alt="" class="img-fluid">
                            </a>
                        </div>
                        <div class="col-md-2">
                            <a href="{{ apartment.image.all.2 }}" data-lightbox="home-images">
                                <img src="{{ apartment.image.all.2 }}" alt="" class="img-fluid">
                            </a>
                        </div>
                        <div class="col-md-2">
                            <a href="{{ apartment.image.all.3 }}" data-lightbox="home-images">
                                <img src="{{ apartment.image.all.3 }}" alt="" class="img-fluid">
                            </a>
                        </div>
                        <div class="col-md-2">
                            <a href="{{ apartment.image.all.4 }}" data-lightbox="home-images">
                                <img src="{{ apartment.image.all.4 }}" alt="" class="img-fluid">
                            </a>
                        </div>
                        <div class="col-md-2">
                            <a href="{{ apartment.image.all.5 }}" data-lightbox="home-images">
                                <img src="{{ apartment.image.all.5 }}" alt="" class="img-fluid">
                            </a>
                        </div>
                    </div>
                    <!-- Fields -->
                    <div class="row mb-5 fields">
                        <div class="col-md-6">
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item text-secondary">
                                    <i class="fas fa-money-bill-alt"></i> Asking Price:
                                    <span class="float-right">{{ apartment.price }}</span>
                                </li>
                                <li class="list-group-item text-secondary">
                                    <i class="fas fa-bed"></i> Bedrooms:
                                    <span class="float-right">{{ apartment.bedrooms }}</span>
                                </li>
                                <li class="list-group-item text-secondary">
                                    <i class="fas fa-bath"></i> Bathrooms:
                                    <span class="float-right">{{ apartment.bathrooms }}</span>
                                </li>
                                <li class="list-group-item text-secondary">
                                    <i class="fas fa-car"></i> Garage:
                                    <span class="float-right">{{ apartment.garage }}
                                    </span>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-6">
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item text-secondary">
                                    <i class="fas fa-th-large"></i> Square Feet:
                                    <span class="float-right">{{ apartment.size }}</span>
                                </li>
                                <li class="list-group-item text-secondary">
                                    <i class="fas fa-square"></i> Lot Size:
                                    <span class="float-right">2.5 Acres
                                    </span>
                                </li>
                                <li class="list-group-item text-secondary">
                                    <i class="fas fa-calendar"></i> Listing Date:
                                    <span class="float-right">{{ apartment.list_date }}</span>
                                </li>
                                <li class="list-group-item text-secondary">
                                    <i class="fas fa-bed"></i> Realtor:
                                    <span class="float-right">Kyle Brown
                                    </span>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div style="margin-left:20px;" id="datepicker3"></div>
                    <!-- Description -->
                    <div class="row mb-5">
                        <div class="col-md-12">
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia recusandae esse reiciendis
                            officia omnis non rerum dicta
                            cupiditate nostrum molestias deserunt aut minus inventore animi atque, consequuntur ad
                            fugit. Possimus culpa
                            blanditiis repellendus ipsa similique ullam, natus error dolor harum.
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div style="background:#2E2E2E;" class="card mb-3">
                        <img class="card-img-top" src="{% static 'assets/img/realtors/kyle.jpg' %}"
                            alt="Seller of the month">
                        <div class="card-body">
                            <h5 style="color:white;" class="text-secondary card-title">Property Realtor</h5>
                            <h6 style="color:white;" class="">Kyle Brown</h6>
                        </div>
                    </div>

                    <h3 style="margin-top:20px;">Choose dates</h3>
                    <div style="margin-top:20px;" class="pick-dates-div">
                        <form method="POST" class="post-form">{% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="form-btn save btn btn-default">Send</button>
                        </form>
                        <button style="margin-top: 25px;" class="btn-primary btn-block btn-lg" data-toggle="modal"
                            data-target="#inquiryModal">More
                            Questions ?</button>
                    </div>
                </div>

            </div>
        </div>
    </section>

    <!-- Inquiry Modal -->
    <div class="modal fade" id="inquiryModal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="inquiryModalLabel">Make An Inquiry</h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <span>&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="property_name" class="col-form-label">Property:</label>
                            <input type="text" name="listing" class="form-control" value="45 Drivewood Cirlce" disabled>
                        </div>
                        <div class="form-group">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" name="name" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label for="email" class="col-form-label">Email:</label>
                            <input type="email" name="email" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label for="phone" class="col-form-label">Phone:</label>
                            <input type="text" name="phone" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="message" class="col-form-label">Message:</label>
                            <textarea name="message" class="form-control"></textarea>
                        </div>
                        <hr>
                        <input type="submit" value="Send" class="btn btn-block btn-secondary">
                    </form>
                </div>
            </div>
        </div>
    </div>


    <!-- Footer -->
    <footer id="main-footer" class="py-4 bg-primary text-white text-center">
        Copyright &copy;
        <span class="year"></span> BT Real Estate
    </footer>




</body>

{% endblock %}

django_news_blog/templates/booking/apartments.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'assets/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

    <title>BT Real Estate</title>
</head>

<body>
    <!-- Top Bar -->
    <section id="top-bar" class="p-3">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <i class="fas fa-phone"></i> (617)-555-5555
                </div>
                <div class="col-md-4">
                    <i class="fas fa-envelope-open"></i> contact@btrealestate.co
                </div>
                <div class="col-md-4">
                    <div class="social text-right">
                        <a href="#">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a href="#">
                            <i class="fab fa-facebook"></i>
                        </a>
                        <a href="#">
                            <i class="fab fa-linkedin"></i>
                        </a>
                        <a href="#">
                            <i class="fab fa-instagram"></i>
                        </a>
                        <a href="#">
                            <i class="fab fa-pinterest"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Navbar -->


    <section id="showcase-inner" class="py-5 text-white">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-12">
                    <h1 class="display-4">Browse Our Properties</h1>
                    <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
                </div>
            </div>
        </div>
    </section>

    {% include "partials/_navbar_booking.html" %}

    <!-- Breadcrumb -->
    <section id="bc" class="mt-3">
        <div class="container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="/booking/">
                            <i class="fas fa-home"></i> Home</a>
                    </li>
                    <li class="breadcrumb-item active"> Browse Listings</li>
                </ol>
            </nav>
        </div>
    </section>

    <!-- Listings -->
    <section id="listings" class="py-4">
        <div class="container">
            <h1 style="margin-bottom:25px; margin-top:30px;" class="heading">All listings</h1>
            <div style="margin-bottom:25px;" class="row">
                {% for apartment in apartment_list %}
                <!-- Listing 1 -->
                <div class="col-md-6 col-lg-4 mb-4">
                    <div class="card listing-preview">
                        <img class="card-img-top" src="{{ apartment.photo_main.url }}" alt="">
                        <div class="card-img-overlay">
                            <h2>
                                <span class="badge badge-secondary text-white">${{ apartment.price }} </span>
                            </h2>
                        </div>
                        <div class="card-body divbg">
                            <div class="listing-heading text-center">
                                <h4 class="text-primary">{{ apartment.address }}y</h4>
                                <p>
                                    <i class="fas fa-map-marker text-secondary"></i> {{ apartment.state }}</p>
                            </div>
                            <hr>
                            <div class="row py-2 text-secondary">
                                <div class="col-6">
                                    <i class="fas fa-th-large"></i> Sqft: {{ apartment.size }}</div>
                                <div class="col-6">
                                    <i class="fas fa-car"></i> Garage: {{ apartment.garage }}</div>
                            </div>
                            <div class="row py-2 text-secondary">
                                <div class="col-6">
                                    <i class="fas fa-bed"></i> Bedrooms: {{ apartment.bedrooms }}</div>
                                <div class="col-6">
                                    <i class="fas fa-bath"></i> Bathrooms: {{ apartment.bathrooms }}</div>
                            </div>
                            <hr>
                            <div class="row py-2 text-secondary">
                                <div class="col-6">
                                    <i class="fas fa-user"></i> Kyle Brown</div>
                            </div>
                            <div class="row text-secondary pb-2">
                                <div class="col-6">
                                    <i class="fas fa-clock"></i> {{ apartment.list_date }}</div>
                            </div>
                            <hr>
                            <a href="{% url 'booking:apartment' apartment.id %}" class="btn btn-primary btn-block">More
                                Info</a>
                        </div>
                    </div>
                </div>

                {% endfor %}


                <div class="row">
                    <div class="col-md-12">
                        <ul class="pagination">
                            <li class="page-item disabled">
                                <a class="page-link" href="#">&laquo;</a>
                            </li>
                            <li class="page-item active">
                                <a class="page-link" href="#">1</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#">2</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#">3</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#">&raquo;</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
    </section>

    <!-- Footer -->
    <footer id="main-footer" class="py-4 bg-primary text-white text-center">
        Copyright &copy;
        <span class="year"></span> BT Real Estate
    </footer>

    <script src="assets/js/jquery-3.3.1.min.js "></script>
    <script src="assets/js/bootstrap.bundle.min.js "></script>
    <script src="assets/js/main.js "></script>
</body>

{% endblock %}

django_news_blog/templates/booking/make_reservation.html
Make a reservation

<form method="POST" class="post-form">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="form-btn save btn btn-default">Send</button>
</form>